// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.4.0.0
//      SpecFlow Generator Version:3.4.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecflowTests.FeatureFiles
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.4.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Functions")]
    public partial class FunctionsFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "Functions.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "FeatureFiles", "Functions", "\tIn order to avoid silly mistakes\r\n\tAs a math idiot\r\n\tI want to be told the sum o" +
                    "f two numbers", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 6
#line hidden
#line 7
testRunner.Given("Start app", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add two numbers")]
        [NUnit.Framework.CategoryAttribute("add")]
        [NUnit.Framework.TestCaseAttribute("33", "5", "38", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("0", "4", "4", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("0", "0", "0", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("20", "5", "25", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("-4", "5", "1", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("21", "-5", "16", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("-3", "-5", "-8", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("111111111", "222222222", "333333333", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("1,4", "5", "6,6", new string[] {
                "double"}, Category="double")]
        [NUnit.Framework.TestCaseAttribute("2", "2,4", "4,4", new string[] {
                "double"}, Category="double")]
        [NUnit.Framework.TestCaseAttribute("3,1", "2,1", "5,2", new string[] {
                "double"}, Category="double")]
        [NUnit.Framework.TestCaseAttribute("0,1", "2,1", "2,2", new string[] {
                "double"}, Category="double")]
        [NUnit.Framework.TestCaseAttribute("3,2", "0,1", "3,3", new string[] {
                "double"}, Category="double")]
        [NUnit.Framework.TestCaseAttribute("3,02", "1,1", "3,12", new string[] {
                "double"}, Category="double")]
        [NUnit.Framework.TestCaseAttribute("5,2", "0,01", "5,21", new string[] {
                "double"}, Category="double")]
        public virtual void AddTwoNumbers(string first, string second, string result, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "add"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("first", first);
            argumentsOfScenario.Add("second", second);
            argumentsOfScenario.Add("result", result);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add two numbers", null, tagsOfScenario, argumentsOfScenario);
#line 10
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 11
 testRunner.When(string.Format("the two numbers  \"{0}\" and \"{1}\" are added", first, second), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 12
 testRunner.Then(string.Format("the result should be \"{0}\"", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Minus two numbers")]
        [NUnit.Framework.CategoryAttribute("minus")]
        [NUnit.Framework.TestCaseAttribute("0", "0", "0", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("0", "4", "-4", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("5", "0", "5", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("5", "4", "1", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("5", "8", "-3", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("6", "6", "0", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("50", "5", "45", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("-5", "4", "-9", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("3", "-2", "5", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("-7", "-1", "6", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("-1", "-1", "0", new string[] {
                "integer"}, Category="integer")]
        [NUnit.Framework.TestCaseAttribute("3", "1,3", "1,7", new string[] {
                "double"}, Category="double")]
        [NUnit.Framework.TestCaseAttribute("5,5", "4", "1,5", new string[] {
                "double"}, Category="double")]
        [NUnit.Framework.TestCaseAttribute("4", "0,4", "3,6", new string[] {
                "double"}, Category="double")]
        [NUnit.Framework.TestCaseAttribute("0,1", "3", "-2,9", new string[] {
                "double"}, Category="double")]
        [NUnit.Framework.TestCaseAttribute("0,03", "3", "-2,97", new string[] {
                "double"}, Category="double")]
        [NUnit.Framework.TestCaseAttribute("2", "2,01", "0,01", new string[] {
                "double"}, Category="double")]
        public virtual void MinusTwoNumbers(string first, string second, string result, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "minus"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("first", first);
            argumentsOfScenario.Add("second", second);
            argumentsOfScenario.Add("result", result);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Minus two numbers", null, tagsOfScenario, argumentsOfScenario);
#line 39
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 6
this.FeatureBackground();
#line hidden
#line 40
 testRunner.When(string.Format("the two numbers  \"{0}\" and \"{1}\" are minused", first, second), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 41
 testRunner.Then(string.Format("the result should be \"{0}\"", result), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
